### ISSUE TITLE
`Pass.ts` does not include `view` in `get descriptor` so we're unable to render to texture

### ISSUE THREAD

**Issue by philogb** [dmnsgn/dgel#10]
When generating the descriptor object, the `Pass` class does not check whether there is a `view` attribute in the `Attachment` objects (around line 19 of Pass.ts).

Because of this current view is always used by `Context.ts` (line 115) which makes the framework unable to render stuff directly to a texture.

**Comment by philogb** [comment]
I was able to workaround this by using the WebGPU API directly to create a render pass:

<img width="525" alt="Screen Shot 2021-12-15 at 12 32 17 AM" src="https://user-images.githubusercontent.com/71751/146129113-2ce8822f-eb69-4160-828d-5ea1a9eed05b.png">

But I am still getting an error:

<img width="840" alt="Screen Shot 2021-12-15 at 12 33 21 AM" src="https://user-images.githubusercontent.com/71751/146129215-cf8c6ca8-4182-4406-8388-6983f76ac0ea.png">

which I spent too many hours debugging. I looked into fragment targets in renderpipeline and made sure they are the same format than the textures being created for the output. I also have been mostly comparing the code with the deferred rendering code [here](https://github.com/austinEng/webgpu-samples/blob/main/src/sample/deferredRendering/main.ts).

Another issue I found is that it looks like the output texture has to be included in a bindgrouplayout, but [the shader](https://github.com/austinEng/webgpu-samples/blob/main/src/sample/deferredRendering/fragmentWriteGBuffers.wgsl) sets the type of the output texture as `vec4` and not `texture2d`. Which I believe might be another issue for us given we create the variable definitions based on the BindGroupLayout information. 

All this to say that maybe a simple example demonstrating rendering to a texture might go a long way in making the framework more robust for these use-cases.

**Comment by dmnsgn** [comment]
I have revamped the Attachment object so you're able to pass an object with the new options op/view/resolveTarget as second argument after the value, and updated the Pass getter: `new Attachment({ r: 0.07, g: 0.07, b: 0.07, a: 1 }, { view: yourView })`

> All this to say that maybe a simple example demonstrating rendering to a texture might go a long way in making the framework more robust for these use-cases.

Agreed, the examples are few for now as my availability is limited but a RTT example could help for deferred and post processing.

**Comment by dmnsgn** [comment]
Added a RTT example which renders a cube (with uv texture) to a texture and use it as another pass' cube texture : https://dmnsgn.github.io/dgel/?id=render-to-texture

To sum up:
- the format of the RTT texture here is "rgba32float"
  - it is unfilterable so the BindGroupLayout needs an entries with sampleType defined as `texture: { sampleType: "unfilterable-float" },`
  - the pipeline of the command rendering to a RTT pass needs to set its `fragmentTargets` with this format
  - the pipeline program entrypoint "main" return value is defined by `pipeline.fragmentOuts` so that's where you map the targets (here just a f32 color, but can be any gbuffer you want with maximum <= 8)
- the rttTexture needs to have `RENDER_ATTACHMENT` and `TEXTURE_BINDING` usages
- the rttCommand pass needs a view created from this texture with the same format
- the `drawGeometryCommand` needs this view as a resource in one of its BindGroup

Most of the code here:
https://github.com/dmnsgn/dgel/blob/f78974b155d617460006acb669827913f3ebbb32/examples/render-to-texture.js#L261-L285

Quirks:
- uv.y needs to be flipped in textureLoad
- everything is triggered on resize as it doesn't look like you can reset a texture size without recreating it
- the process feels a bit inelegant but I assume that might be the job of a higher abstraction in the future

**Comment by philogb** [comment]
Thank you!
